name: flutter_iiko_app
description: "Flutter app. The main goal of the application is to provide a convenient interface for interacting with the iiko API, which is widely used in restaurants and cafés for managing orders, deliveries, and logistics."
publish_to: 'none'

version: 1.0.0+1

repository: https://github.com/ultra-rony/flutter_iiko_app
homepage: https://github.com/ultra-rony/flutter_iiko_app

owner:
  name: Romain Diakonov
  email: i@rodrix.ru

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get_it: ^9.0.5
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  logger: ^2.6.2
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  injectable: ^2.6.0
  auto_route: ^10.2.0
  google_fonts: ^6.3.2
  path: ^1.9.1
  sqflite: ^2.4.2
  hydrated_bloc: ^11.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.1
  auto_route_generator: ^10.2.5
  json_serializable: ^6.11.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

